name: SimpleColorMOTD
version: 3.0
main: com.xurame.ServerMOTD.MOTD
description: A super simple MOTD plugin!
 
commands:
    motd:
        usage: /<command>
        description: View MOTD
    setmotd:
        usage: /<command>
        description: Set MOTD
    setservermotd:
        usage: /<command>
        description: Set system MOTD
       
permissions:
    motd.*:
       description: Use all MOTD commands.
       children:
           motd.check: true
           motd.set: true
       default: op
    motd.check:
        description: Check the MOTD.
        default: true
    motd.set:
        description: Use the setmotd command to change the MOTD.
        default: op
